### ISSUE TITLE
Save transformation result as an ITK transform file

### ISSUE THREAD

**Issue by lassoan** [SuperElastix/elastix#18]
Since Elastix support has been added to 3D Slicer, we tried it many registration tasks and it works really well. However, there is one significant inconvenience: we can only save transformation as a displacement field.

Is there a way to save computed transforms as regular ITK transform file?

We prefer the .hdf5 file format that can store a sequence of transforms of any types in a single file, but a saving each into a separate file would be usable, too.

**Comment by marly892** [comment]
I agree it would be really useful, in my case I would need to call Elastix inside my module and use the output transformation for further processing.

**Comment by che85** [comment]
I agree with @lassoan. 

Is there a way to get the outputs(volumes, transforms) for all (rigid, affine, bSpline)? I am asking that because we are currently using BRAINS registration during prostate biopsies[1] and basically we are  giving users the option to select the registration results of rigid, affine and bSpline during evaluation in order to select the best registration result.  

We would like to evaluate the Elastix and this context to see if the registration results are better. 

[1] https://github.com/SlicerProstate/SliceTracker

**Comment by fedorov** [comment]
Yes, this feature would be very useful. I communicated with @mstaring about this issue back in 2010, and at that time, support of ITK transforms was item 38 on the elastix ToDo list (http://elastix.bigr.nl/wiki/index.php/To_do, the page does not exist anymore).

**Comment by mstaring** [comment]
Hi all,
I agree this is a very useful feature to have!
I think what would be needed is to build an option in the ReadFromFile() and WriteToFile() functions in elastix to use the ITK transform writer functionality. I could give further pointers if needed. Is anyone interested in implementing such a feature?
Best, Marius

**Comment by mstaring** [comment]
@che85 it is already possible to get these results, but they are in a proprietary format that we made up ourselves. transformix can deal with it however, so you can generate DVFs, warped images and warped segmentations, etc.

**Comment by lassoan** [comment]
@mstaring ElastiX seems to perform very well in ultrasound image time sequence registration and the main issue is that the sequence of computed displacement fields takes about 8GB memory. So, we are very interested in implementing ITK export of rigid and bspline transforms and ready to work on it.

Can you give some pointers how to get started?

I would prefer to use standard ITK transform IO to write transforms to file. For this, we would need to create ITK transforms.

I guess we would keep Elastix transform reading/writing as is, using the current private file format. ITK transform reading/writing would be just some additional import/export option. Maybe we can even create a separate executable for converting between Elastix and ITK transform files?

**Comment by lassoan** [comment]
Guys, can we help us get started with this? Thank you!

**Comment by kaspermarstal** [comment]
@lassoan Sure, we will discuss this at out next sprint meeting and get back to you!

**Comment by lassoan** [comment]
Sounds good, thank you!

**Comment by lassoan** [comment]
By the way, I've asked this again because yet another group wanted to use Elastix but they would need registration result as a linear transform and not as a displacement field.

**Comment by FBerendsen** [comment]
We talked on this a little and these are some hints to get started. Maybe others can add here as well.

After running elastix registration the chain of transforms are in a AdvancedCombinationTransform which you should be able to access in the itkfilter-style interface class of elastix. I can think of two approaches, which depend what type of itk tranfrom you want and how you want to use it:

1) Since the transforms (and combinations thereof) in elastix are derived from itkTransform you could try to expose that (smartpointer). The transform base class, as defined in elastix, is called itkAdvancedTransform and is derived from itkTransform. However, these itkv4 functions are currently not implemented in the itkAdvancedTransform:
  void ComputeJacobianWithRespectToParameters( ... )
  void ComputeJacobianWithRespectToPosition( ... )
This probably means that you can use this itkTransform in e.g. a resampler where you don't need derivatives. But, using an itkTransformWriter on this or using it in an optimizer will fail.

2) To convert from an AdvancedCombinationTransform (elastix) to an CompositeTransform (itk) you could combine the logic of these copiers made by @dpshamonin:
Common\OpenCL\Filters\itkGPUAdvancedCombinationTransformCopier
Common\OpenCL\Filters\itkGPUCompositeTransformCopier
Here, copying is implemented for the most common transforms (e.g. rigid, affine, bspline).
Using this, a new converter class may be written (elastixTransformToItkTranformConverter?) that 1) converts each sub transform of the AdvancedCombination from an elastix class to an itk class and 2) puts them in an CompositeTransform. We think that instead of calling GPUAdvancedAffineTransformType::New(); you would need to call itk::AffineTransformType::New();. Elastix' class for BSpline transforms (AdvancedBSplineTransform) is not derived from itk's BSpline transform class, but I understood that its parameters are defined identically and can be transfered. The same hold for the other transforms.

**Comment by mstaring** [comment]
so a pipeline could be:
- after each elastix Run() you do GetFinalTransform(), which should get you a pointer to an itk::AdvancedCombinationTransform to be found in Common/Transforms
- Convert the itk::AdvancedCombinationTransform in an itk::CompositeTransform, indeed using & modifying functionality from Common\OpenCL\Filters
- Get each sub-transform from the itk::CompositeTransform and export them to disk using the itk::TransformFileWriter (or perhaps it can work on the itk::CompositeTransform directly)

If you got such a pipeline working, we can find a suitable place in elastix to put it.

**Comment by mstaring** [comment]
I'm closing this issue now due to the inactivity, but feel free to reopen.
