### ISSUE TITLE
Linking error when trying to build project with elastix 5.0.1

### ISSUE THREAD

**Issue by ntatsisk** [SuperElastix/elastix#327]
Hello, I upgraded to elastix 5.0.1 and ITK 5.1.1 (with ITK_LEGACY_REMOVE ON) from elastix 5.0.0. The build for both libraries was successful but when I tried to build my own project I got an error stating that it cannot link to "elastix.lib". However, I noticed there is no "elastix.lib" library but rather "elastix-5.0.lib".

The solution for me was to change the line: 

[https://github.com/SuperElastix/elastix/blob/90122eff6b37a17adc9f5bb3d7bc08608e9c14a6/Core/CMakeLists.txt#L198](https://github.com/SuperElastix/elastix/blob/90122eff6b37a17adc9f5bb3d7bc08608e9c14a6/Core/CMakeLists.txt#L198) 

to 

`set( ELASTIX_LIBRARIES elastix_lib transformix_lib PARENT_SCOPE )`

<br/><br/>

Setup:
* Windows 10
* VS 2017
* CMake 3.17.2
* Release mode

**Comment by N-Dekker** [comment]
@ntatsisk Thanks for reporting this issue, Konstantinos! Your solution looks good to me  😃  Do you want to make it a pull request? Or would you prefer us to fix the issue?

For the record, the convention of adding the elastix major and minor version to library file names was already here in version 4.9.0: https://github.com/SuperElastix/elastix/blob/4.9.0/CMake/elastixExportTarget.cmake#L16 I made some adjustments for version 5.0.1, in order to support building exe and lib of elastix and transformix together: https://github.com/SuperElastix/elastix/blob/5.0.1/CMake/elastixExportTarget.cmake#L18 But I think those adjustments did not fundamentally change the library naming conversion of elastix.

**Comment by ntatsisk** [comment]
Thanks for the info, feel free to fix the issue without a pull request from my side!
