### ISSUE TITLE
AffineDTITransform does not return the CenterOfRotationPoint 

### ISSUE THREAD

**Issue by dyliu2016** [SuperElastix/elastix#366]
Hi，
The AffineDTITransform seems does not set the CenterOfRotationPoint to ”TransformParametersMap“ correctly when using elastix 5 as lib. The registration works fine but when I tried to use transformix with the TransformParametersMap，error occured like this：

ERROR: No center of rotation is specified in the transform parameter file

--------------- Exception ---------------

itk::ExceptionObject (00000048F1CFEB60)
Location: "unknown"
File: D:\xxx\elastix-5.0.1\Components\Transforms\AffineDTITransform\elxAffineDTITransform.hxx
Line: 87
Description: itk::ERROR: itk::ERROR: AffineDTITransformElastix(0000014DBA10EB90): Transform parameter file is corrupt.

-----------------------------------------
Errors occurred

any hint？

**Comment by N-Dekker** [comment]
@dyliu2016 We closed the issue now, as we think it is fixed by pull request https://github.com/SuperElastix/elastix/pull/379 "Add missing parameters to transform parameter maps", which is just merged onto the https://github.com/SuperElastix/elastix develop branch. If you have the time, please check it out! And of course, if you think the issue is not entirely fixed, please feel free to reopen the issue, or submit another one.

Thanks for reporting this issue!
