### ISSUE TITLE
Program can not exit normally

### ISSUE THREAD

**Issue by GreateLi** [SuperElastix/elastix#374]
MFC Project Program can not exit normally

**Comment by N-Dekker** [comment]
How did you create your MFC Project Program? Do you think the problem is related to SuperElastix/elastix?

**Comment by GreateLi** [comment]
@N-Dekker 
  I used new version  it show ;i'm found the problem itk threadpool (itk5).

**Comment by N-Dekker** [comment]
Thank you @GreateLi As you found the problem is in ITK5 threadpool, I assume that it is not a specific SuperElastix/elastix problem, and I'll close your issue.

Of course, if you think it's an ITK problem, you might still submit to https://github.com/InsightSoftwareConsortium/ITK/issues but then you must be more specific, and tell us exactly how we could reproduce the problem.

Kind regards, Niels
