### ISSUE TITLE
Documenting install via Docker

### ISSUE THREAD

**Issue by RGologorsky** [SuperElastix/elastix#440]
Hi, could instructions please be posted on how to install / configure Elastix via the Docker image on Dockerhub? I looked in the Getting Started portion of the docs (https://simpleelastix.readthedocs.io/GettingStarted.html) and saw great instructions for setting up Elastix via CMake etc but not for Docker. I would like to install / configure Elastix via Docker and import it into a Jupyter notebook. Documentation on setup much appreciated.

Thank you!

**Comment by ViktorvdValk** [comment]
Hi, on the elastix repository on [DockerHub](https://hub.docker.com/repository/docker/superelastix/elastix) you can find a detailed readme on how to use and pull the docker image to use on you local machine via the command line.

If you want to use elastix in a jupyter notebook I would suggest having a look at the [ITKElastix package](https://github.com/InsightSoftwareConsortium/ITKElastix), rather than the docker image. ITKElastix is available on Pypi and can easily be installed with `pip install itk-elastix`. See the [example notebooks](https://github.com/InsightSoftwareConsortium/ITKElastix/blob/master/examples/ITK_Example01_SimpleRegistration.ipynb) for using itk-elastix in a jupyter notebook.
