### ISSUE TITLE
.a files after compiling

### ISSUE THREAD

**Issue by amwink** [SuperElastix/elastix#790]
After downloading ElastiX from here and compiling with CMake, all the binary files, executables and `.a` files, end up in the `bin` directory. My understanding is that `.a` files are for static linking. Two questions about this:

-- does this mean that once the executables are ready, it is safe to delete the `.a` files?
-- is it possible to build all the libraries as dynamic (so have all the current `.a` files as `.so` files) and smaller executables?

**Comment by N-Dekker** [comment]
Thanks for asking, @amwink I'm not a Linux or MacOS expert, but as far as I understand, you may delete the .a files, once they are linked into the executables. You will need to keep the .so files for the ANN library.

The minimum set of files to run elastix for Windows, MacOS, and Linux available as download at https://github.com/SuperElastix/elastix/releases

Because of limited resources, we do not support building all the libraries as dynamic (shared) anymore. Sorry!

Please close the ticket if you think your questions are answered. 😃  Note that we also have a forum for user questions: https://groups.google.com/g/elastix-imageregistration
